### ISSUE TITLE
Add ucg to More Tools

### ISSUE THREAD

**Issue by gvansickle** [petdance/beyondgrep#44]
Hi petdance,

"ucg, UniversalCodeGrep
UniversalCodeGrep is an extremely fast Ack-like search tool.  Written in C++, multithreaded, and  utilizing PCRE's JIT compilation support, it is in some cases faster than grep itself in raw file matching speed.  Supports Ack's user file type definition mechanism."
URL: https://gvansickle.github.io/ucg/

Thanks again,
GRVS https://github.com/gvansickle

**Comment by shlomif** [comment]
@petdance : what do you say? Do you want a pull-req adding it as well? @gvansickle : I'll be sure to check ucg out.

**Comment by petdance** [comment]
Yes, this would be good to have as well.

**Comment by shlomif** [comment]
@petdance - will do , thanks.

**Comment by petdance** [comment]
Added.  Thanks.

**Comment by gvansickle** [comment]
Thanks @petdance !

**Comment by petdance** [comment]
You're welcome.  It only took a year. :-)
