### ISSUE TITLE
Add ack-dev to Community page

### ISSUE THREAD

**Issue by petdance** [petdance/beyondgrep#45]
http://beyondgrep.com/community/ should have ack-dev.

**Comment by petdance** [comment]
Added.  Thanks.

**Comment by shlomif** [comment]
On Fri, 03 Mar 2017 22:48:13 -0800
Andy Lester <notifications@github.com> wrote:

> Added.  Thanks.
> 

Thanks! And you're welcome.

Regards, -- Shlomi Fish

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
My Aphorisms - http://www.shlomifish.org/humour.html

     <rindolf>  We have a saying: “We survived Pharaoh - we’ll survive this.”
 <sorabji5252>  I suppose it’s all cake after Pharaoh.
    — Freenode’s #reddit channel

Please reply to list if it's a mailing list post - http://shlom.in/reply .
