### ISSUE TITLE
pcregrep (for More Tools page)

### ISSUE THREAD

**Issue by n1vux** [petdance/beyondgrep#48]
Ubuntu's patch notes for the pcre library alert me to the existence of **`pcregrep`** aka **`pcre2grep`** and `pcre[2]?test`. Probably worth including when _More Tools_ is updated.
Power of PCRE in a grep guise.  I can't endorse their recommendation of linking pcregrep as grep on a *nix as it will break shell scripts ...but could be useful to some if 'ack' isn't grep-like enough?

Available for Win and Z/OS (EBCDIC!) as well as Linux.

pcre.org
linux.die.net/man/1/pcregrep
www.rexegg.com/pcregrep-pcretest.html
manpages.ubuntu.com/manpages/precise/en/man1/pcregrep.1.html

**Comment by petdance** [comment]
Added.
