### ISSUE TITLE
Scoop for Windows: new packager of ack

### ISSUE THREAD

**Issue by branning** [petdance/beyondgrep#56]
The [Scoop command line installer for Windows](https://github.com/lukesampson/scoop) recently added [an ack app](https://github.com/lukesampson/scoop/blob/master/bucket/ack.json) to its main bucket. Would you consider adding it to the ack site?

``` html
<dt><a href="http://scoop.sh">Scoop for Windows</a></dt>
<dd>App "ack"</dt>
```

Scoop is pretty nice, it kinda like a Homebrew for Windows.

**Comment by petdance** [comment]
Added.  Thanks.
